// Generated by CoffeeScript 1.10.0

/*
  @author Gilles Gerlinger
  Copyright 2016. All rights reserved.
 */

(function() {
  module.exports = {
    tag: 'rpc',
    sse: '_remoteReady',
    sessionTimeOut: 30 * 60 * 1000
  };

}).call(this);
