// Generated by CoffeeScript 1.8.0

/*
  @author Gilles Gerlinger
  Copyright 2015. All rights reserved.
 */

(function() {
  var Response, fetch;

  Response = (function() {
    function Response(data) {
      this.data = data;
    }

    Response.prototype.json = function() {
      return JSON.parse(this.data);
    };

    return Response;

  })();

  module.exports = fetch = function(uri, options) {
    console.log('using own fetch');
    return new Promise(function(resolve, reject) {
      var xhr;
      xhr = new XMLHttpRequest();
      xhr.open(options.method, uri, true);
      xhr.setRequestHeader('Content-type', 'application/json; charset=utf-8');
      xhr.send(options.body || null);
      xhr.onload = function() {
        console.log('got', xhr.response);
        return resolve(new Response(xhr.response));
      };
      return xhr.onerror = function() {
        return reject("xhr error: " + xhr.statusText);
      };
    });
  };

}).call(this);
