// Generated by CoffeeScript 1.8.0

/*
  @author Gilles Gerlinger
  Copyright 2016. All rights reserved.
 */

(function() {
  var __slice = [].slice;

  module.exports = function() {
    var text;
    text = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return console.log.apply(console, [new Date().toLocaleString(), '|'].concat(__slice.call(text)));
  };

}).call(this);
