// Generated by CoffeeScript 1.10.0
(function() {
  var Peer2peer, remotes,
    slice = [].slice;

  remotes = [];

  module.exports = Peer2peer = (function() {
    function Peer2peer() {}

    Peer2peer.prototype._remoteReady = function(remote, uid1) {
      this.remote = remote;
      this.uid = uid1;
      console.log('Peer2peer', this.uid);
      return remotes[this.uid] = this.remote;
    };

    Peer2peer.prototype.invoke = function() {
      var args, method, uid;
      uid = arguments[0], method = arguments[1], args = 3 <= arguments.length ? slice.call(arguments, 2) : [];
      console.log('invoke', uid, method, remotes[uid] != null);
      if (remotes[uid]) {
        if (remotes[uid][method]) {
          return new Promise(function(resolve, reject) {
            var ref;
            return (ref = remotes[uid])[method].apply(ref, args).then(function(rep) {
              console.log(rep);
              return resolve(rep);
            });
          });
        } else {
          throw "method " + method + " is unknown for object " + uid;
        }
      } else {
        throw "no object remote at " + uid;
      }
    };

    return Peer2peer;

  })();

}).call(this);
