// Generated by CoffeeScript 1.10.0

/*
  @author Gilles Gerlinger
  Copyright 2016. All rights reserved.
 */

(function() {
  var Channel, Remote, Rpc, classServer, cnf, json, log;

  log = require('./log');

  cnf = require('./config');

  Rpc = (function() {
    var _return;

    function Rpc(local) {
      this.local = local;
    }

    Rpc.prototype.process = function(msg, res) {
      var e, error, ref, rep;
      log(msg.id + " in", msg);
      if (msg.method === cnf.sse) {
        if (typeof this.local[cnf.sse] === 'function') {
          this.local[cnf.sse](new Remote(Channel.channels[msg.args[0]], msg.args[1]));
          return _return(msg, {
            rep: 'sse OK'
          }, res);
        } else {
          return _return(msg, {
            err: "error: no _remoteReady method for channel " + msg.args[0]
          }, res);
        }
      } else if (this.local[msg.method]) {
        try {
          rep = (ref = this.local)[msg.method].apply(ref, msg.args);
          if (typeof rep["catch"] === 'function') {
            rep.then(function(rep) {
              return _return(msg, {
                rep: rep
              }, res);
            });
            return rep["catch"](function(err) {
              return _return(msg, {
                err: err
              }, res);
            });
          } else {
            return _return(msg, {
              rep: rep
            }, res);
          }
        } catch (error) {
          e = error;
          return _return(msg, {
            err: "error in " + msg.method + ": " + e
          }, res);
        }
      } else {
        return _return(msg, {
          err: "error: method " + msg.method + " is unknown"
        }, res);
      }
    };

    _return = function(msg, rep, res) {
      log(msg.id + " out", rep);
      return res.send(rep);
    };

    return Rpc;

  })();

  classServer = (function() {
    function classServer(classes, timeOut) {
      var Class;
      this.timeOut = timeOut != null ? timeOut : cnf.sessionTimeOut;
      for (Class in classes) {
        this["def " + Class] = {
          Class: classes[Class],
          sessions: []
        };
      }
    }

    classServer.prototype.process = function(Class, msg, res) {
      var rpc, uid;
      uid = msg.id.split('-')[0];
      if (rpc = this["def " + Class].sessions[uid]) {
        clearTimeout(rpc.timeOut);
      } else {
        this["def " + Class].sessions[uid] = rpc = new Rpc(new this["def " + Class].Class());
        this._echo(Class, 'adding', uid);
      }
      rpc.timeOut = setTimeout((function(_this) {
        return function() {
          delete _this["def " + Class].sessions[uid];
          return _this._echo(Class, 'removing', uid);
        };
      })(this), this.timeOut);
      return rpc.process(msg, res);
    };

    classServer.prototype._echo = function(Class, operation, uid) {
      return log(operation + " " + Class + " session " + uid + " (# sessions: " + (Object.keys(this["def " + Class].sessions).length) + ")");
    };

    return classServer;

  })();

  json = function(req, res, next) {
    var body;
    body = [];
    req.on('data', function(chunk) {
      return body.push(chunk);
    });
    return req.on('end', function() {
      req.body = Buffer.concat(body).toString();
      if (req.headers['content-type'] && req.headers['content-type'].indexOf('application/json') > -1) {
        req.body = JSON.parse(req.body);
        if (!res.send) {
          res.send = function(msg) {
            return res.end(JSON.stringify(msg));
          };
        }
      }
      return next();
    });
  };

  module.exports = function(app, classes, options) {
    var Class, fn, server;
    if (options == null) {
      options = {};
    }
    server = new classServer(classes, options.timeOut);
    app.use(json);
    fn = function(Class) {
      log("listening on class " + Class);
      return app.use("/" + Class, function(req, res) {
        return server.process(Class, req.body, res);
      });
    };
    for (Class in classes) {
      fn(Class);
    }
    return app.use("/" + cnf.tag, function(req, res, next) {
      return new Channel(req, res, next);
    });
  };

  Remote = (function() {
    function Remote(_sseChannel, methods) {
      var ctx, fn, i, len, method, ref;
      this._sseChannel = _sseChannel;
      ctx = {
        count: 0,
        uid: Math.random().toString().substring(2, 10)
      };
      ref = methods || [];
      fn = (function(_this) {
        return function(method) {
          return _this[method] = function() {
            return _this._sseChannel.send({
              method: method,
              args: [].slice.call(arguments),
              id: ctx.uid + "-" + (++ctx.count)
            });
          };
        };
      })(this);
      for (i = 0, len = ref.length; i < len; i++) {
        method = ref[i];
        fn(method);
      }
    }

    return Remote;

  })();

  Channel = (function() {
    Channel.channels = [];

    function Channel(req, resp, next) {
      this.resp = resp;
      Channel.channels[this.uid = Number(new Date()).toString()] = this;
      this.resp.statusCode = 200;
      this.resp.setHeader('Content-Type', 'text/event-stream');
      this.resp.setHeader('Cache-Control', 'no-cache');
      this.resp.setHeader('Connection', 'keep-alive');
      this.resp.setHeader('Access-Control-Allow-Origin', '*');
      req.on('close', (function(_this) {
        return function() {
          log('SSE', _this.uid, 'closed');
          delete Channel.channels[_this.uid];
          return _this.closed = true;
        };
      })(this));
      this.send({
        uid: this.uid,
        id: 'SSE'
      });
      if (next) {
        next();
      }
    }

    Channel.prototype.send = function(msg) {
      log(msg.id + " out " + this.uid, msg);
      return this.resp.write("event: " + cnf.tag + "\ndata: " + (JSON.stringify(msg)) + "\n\n");
    };

    return Channel;

  })();

}).call(this);
