// Generated by CoffeeScript 1.10.0
(function() {
  var Customer;

  exports.Customer = Customer = (function() {
    function Customer() {}

    Customer.prototype._remoteReady = function(remote) {
      remote.setMethods(['test']);
      return remote.test('hi there');
    };

    return Customer;

  })();

}).call(this);
