// Generated by CoffeeScript 1.8.0
(function() {
  var Employee;

  module.exports = Employee = (function() {
    function Employee() {}

    Employee.prototype.getProfile = function(name) {
      console.log('getProfile of', name);
      return {
        age: 32,
        email: 'john@acme.com'
      };
    };

    return Employee;

  })();

}).call(this);
