// Generated by CoffeeScript 1.10.0
(function() {
  var Employee, Promise, Remote, chat, count, log,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  if (typeof Promise === 'undefined') {
    Promise = require('avs-easyrpc').Promise;
  }

  log = require('avs-easyrpc').log;

  Remote = require('avs-easyrpc').sseRemote;

  chat = [];

  count = 0;

  exports.Employee = Employee = (function(superClass) {
    extend(Employee, superClass);

    function Employee() {
      Employee.__super__.constructor.call(this, ['echo']);
    }

    Employee.prototype._remoteReady = function(remote) {
      this.remote = remote;
    };

    Employee.prototype.speak = function(msg) {
      var member;
      for (member in chat) {
        if (chat[member].channel.closed) {
          delete chat[member];
        }
      }
      if (!this.alias) {
        chat[this.alias = "joe-" + (++count)] = this;
      }
      for (member in chat) {
        chat[member].remote.echo(this.alias, msg);
      }
      return 'OK';
    };

    Employee.prototype.getProfile = function(name) {
      return new Promise(function(resolve, reject) {
        return setTimeout((function() {
          return resolve({
            age: 32,
            email: 'john@acme.com'
          });
        }), 3000);
      });
    };

    return Employee;

  })(Remote);

}).call(this);
