// Generated by CoffeeScript 1.10.0

/*
  @author Gilles Gerlinger
  Copyright 2016. All rights reserved.
 */

(function() {
  var fs, routes, tag;

  fs = require('fs');

  routes = [];

  tag = '';

  module.exports = function() {
    var app;
    app = function(req, res) {
      var body;
      body = [];
      req.on('data', function(chunk) {
        return body.push(chunk);
      });
      return req.on('end', function() {
        var route;
        if (route = routes[req.url]) {
          req.body = Buffer.concat(body).toString();
          if (req.url !== tag) {
            req.body = JSON.parse(req.body);
          }
          res.send = function(msg) {
            return res.end(JSON.stringify(msg));
          };
          return route(req, res);
        } else {
          return fs.readFile("./" + req.url, function(err, data) {
            res.statusCode = !err ? 200 : 404;
            return res.end(data);
          });
        }
      });
    };
    app.post = function(path, route) {
      return routes[path] = route;
    };
    app.get = function(path, route) {
      return routes[tag = path] = route;
    };
    app.use = function() {};
    return app;
  };

}).call(this);
