// Generated by CoffeeScript 1.10.0
(function() {
  var Remote, Test, expose, p2p, remote, url,
    slice = [].slice;

  Remote = require('avs-easyrpc').Remote;

  expose = require('avs-easyrpc').expose;

  url = 'http://localhost:4145';

  remote = new Remote({
    "class": 'Employee',
    methods: ['getProfile', 'speak'],
    url: url
  });

  Test = (function() {
    function Test() {}

    Test.prototype.echo = function() {
      var text, user;
      user = arguments[0], text = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      console.log.apply(console, [user + ":"].concat(slice.call(text)));
      return 45;
    };

    return Test;

  })();


  /*
  remote = new Remote class:'doesnotexist', methods:['test'], url:url
  remote.test()
  .then (rep) -> console.log 'then', rep
  .catch (err) -> console.log 'cath', err
   */

  p2p = new Remote({
    "class": 'Peer 2 Peer',
    url: url
  });

  expose(new Test(), p2p, url).then(function(source) {
    var bob;
    console.log('p2p', source.remoteID);
    bob = new Remote({
      "class": 'Peer 2 Peer',
      methods: ['echo', 'test'],
      url: url,
      use: source.remoteID
    });
    return bob.echo('bob', {
      msg: 'Hello for peer 1234'
    });
  });

}).call(this);
