// Generated by CoffeeScript 1.10.0

/*
  @author Gilles Gerlinger
  Copyright 2016. All rights reserved.
 */

(function() {
  var express, expressRpc, http, parser, port, store;

  http = require('http');

  express = require('express');

  parser = require('body-parser');

  store = express();

  store.use(express["static"](__dirname + '/'));

  store.use(parser.json({
    limit: '512kb'
  }));

  store.use(function(err, req, res, next) {
    log(err.stack);
    return next(err);
  });

  expressRpc = require('avs-easyrpc').Server;

  port = 4145;

  http.createServer(store).listen(port, function() {
    console.log("Server started at " + port, new Date(), '\n');
    return expressRpc(store, {
      Employee: require('./employee'),
      Customer: require('./customer')
    }, {
      timeOut: 10 * 60 * 1000
    });
  });

}).call(this);
