// Generated by CoffeeScript 1.10.0
(function() {
  var remotes, seeRet;

  remotes = [];

  module.exports = seeRet = (function() {
    function seeRet() {}

    seeRet.prototype._remoteReady = function(remote) {
      this.remote = remote;
      this.remote.get(35).then(function(rep) {
        return console.log('johnny', rep);
      });
      return this.remote.get(351).then(function(rep) {
        return console.log('be good', rep);
      });
    };

    return seeRet;

  })();

}).call(this);
