// Generated by CoffeeScript 1.10.0
(function() {
  var Remote, Test, expose, remote,
    slice = [].slice;

  Remote = require('avs-easyrpc').Remote;

  expose = require('avs-easyrpc').expose;

  module.exports = remote = new Remote({
    "class": 'Employee',
    methods: ['getProfile', 'speak']
  });

  Test = (function() {
    function Test() {}

    Test.prototype.echo = function() {
      var text, user;
      user = arguments[0], text = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      console.log.apply(console, [user + ":"].concat(slice.call(text)));
      return $('#messages').append($('<li>').text(user + ":" + text[0]));
    };

    return Test;

  })();

  expose(new Test(), remote).then(function() {
    return remote.speak('hello');
  });

  remote.prespeak = function() {
    remote.speak($('#m').val());
    return $('#m').val('');
  };


  /*
  remote.getProfile 'john'
  .then (rep) -> console.log rep
  .catch (err) -> console.log err
  
  remote.publish()
  .then (rep) -> console.log rep
  .catch (err) -> console.log err
   */

}).call(this);
